[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "powerview.py"
description = "Lovely Spam! Wonderful Spam!"
readme = "README.md"
license = {file = "LICENSE.txt"}
version = "2024.0.0"
authors = [
  {name = "Aniq"},
  {name = "Ali"},
]
dependencies = [
  'ldap3@git+https://github.com/ThePirateWhoSmellsOfSunflowers/ldap3.git@tls_cb_and_seal_for_ntlm',
  'dnspython',
  'future',
  'gnureadline',
  'impacket',
  'validators',
  'dsinternals',
  'pycryptodome',
  'chardet',
  'tabulate',
  'gssapi',
]
requires-python = ">= 3.8"
classifiers=[
        'Intended Audience :: Information Technology',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
]

[project.urls]
Repository = "https://github.com/aniqfakhrul/powerview.py"

[project.scripts]
powerview = "powerview:main"
