[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "powerview.py"
description = "Just another powerview alternative"
readme = "README.md"
license = {file = "LICENSE"}
version = "2024.0.0"
authors = [
  {name = "Aniq Fakhrul"},
  {name = "Ali Akbar"},
]
requires-python = ">= 3.8"
classifiers=[
        'Intended Audience :: Information Technology',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
]
dependencies = [
  'impacket',
  'ldap3 @ git+https://github.com/H0j3n/ldap3.git@powerview.py_match-requirements',
  'dnspython',
  'future',
  'gnureadline',
  'validators',
  'dsinternals',
  'chardet',
  'tabulate',
]

[project.urls]
Repository = "https://github.com/aniqfakhrul/powerview.py"

[project.scripts]
powerview = "powerview:main"
